In [71]:
 import os
import math
import numpy as np
os.getcwd()

f = open('/Users/doyoung/Downloads/ToyotaCorolla.txt', 'r', encoding='utf-8')
data = f.readlines()
f.close()

xy = []

for i in range (len(data)):
    data[i]=data[i].replace(',', '.')
    xy.append(data[i].split('\t'))
    
for i in range(1, len(xy)):
    xy[i][1]=xy[i][1].replace('\'','')


In [72]:
for i in range(1, len(xy)):
    xy[0][1] = xy[0][1].rstrip()
    xy[0][2] = xy[0][2].rstrip()
    xy[0][3] = xy[0][3].rstrip()
    xy[0][4] = xy[0][4].rstrip()
    xy[0][5] = xy[0][5].rstrip()
    xy[0][6] = xy[0][6].rstrip()
    
    xy[i][1] = int(xy[i][1])
    xy[i][2] = int(xy[i][2])
    xy[i][3] = int(xy[i][3])
    xy[i][4] = int(xy[i][4])
    xy[i][5] = int(xy[i][5])
    xy[i][6] = int(xy[i][6])

In [73]:
data_x1=[]
data_x2=[]
data_x3=[]
data_x4=[]
data_x5=[]
data_y=[]
data_array = []
data1 = []

for i in range(1,len(xy)):
    data_y.append(xy[i][1])
    
    data_x1.append(xy[i][2])
    data_x2.append(xy[i][3])
    data_x3.append(xy[i][4])
    data_x4.append(xy[i][5])
    data_x5.append(xy[i][6])
    data1.append(1)
    
    data_array.append([xy[i][1], xy[i][2], xy[i][3], xy[i][4], xy[i][5], xy[i][6]])
#data_array = np.array(data_array)

In [74]:
#rand = np.random.RandomState(100)
#rand.shuffle(data_array)

x_array=[]
y_array=[]
for i in range(0, len(data_array)):
    #y_array.append(data_array[i][0])
    #x_array.append(data_array[i][1])
    #x_array.append(data_array[i][2])
    #x_array.append(data_array[i][3])
    #x_array.append(data_array[i][4])
    #x_array.append(data_array[i][5])
    y_array.append([data_array[i][0]])
    x_array.append([data_array[i][1],data_array[i][2],data_array[i][3],data_array[i][4],data_array[i][5],data1[i]])

In [75]:
rand = np.random.RandomState(100)
rand.shuffle(data_array)

In [76]:
data_y = []
for i in range(0, len(data_array)):
    data_y.append([data_array[i][0]])
data_y

[[15250],
 [8250],
 [12950],
 [9750],
 [8800],
 [8150],
 [13750],
 [6150],
 [13950],
 [8250],
 [13995],
 [7850],
 [10950],
 [5950],
 [17795],
 [5950],
 [12950],
 [12950],
 [16250],
 [9950],
 [11950],
 [8995],
 [11930],
 [11950],
 [9450],
 [10950],
 [7750],
 [8250],
 [9995],
 [7250],
 [8500],
 [11750],
 [9800],
 [18950],
 [7995],
 [8950],
 [7750],
 [7500],
 [11950],
 [11750],
 [7250],
 [7950],
 [7950],
 [12950],
 [9900],
 [9200],
 [10950],
 [7950],
 [9950],
 [14750],
 [10900],
 [11480],
 [10950],
 [10250],
 [19250],
 [11450],
 [19600],
 [7450],
 [12695],
 [10950],
 [21950],
 [7750],
 [13950],
 [11950],
 [9450],
 [18900],
 [9950],
 [13450],
 [10750],
 [8950],
 [9950],
 [7950],
 [8950],
 [21950],
 [9950],
 [9950],
 [8450],
 [11690],
 [9250],
 [8950],
 [10500],
 [8800],
 [10750],
 [9950],
 [19900],
 [12900],
 [8750],
 [7500],
 [11495],
 [8950],
 [6450],
 [8745],
 [7400],
 [11495],
 [11250],
 [7450],
 [11710],
 [12950],
 [9500],
 [8750],
 [10950],
 [8950],
 [7450],
 [9950],
 [8450],
 [8250]

In [77]:
data_x = []
for i in range(0, len(data_array)):
    #data_x.append(data_array[i][1])
    #data_x.append(data_array[i][2])
    #data_x.append(data_array[i][3])
    #data_x.append(data_array[i][4])
    #data_x.append(data_array[i][5])
    data_x.append([data_array[i][1],data_array[i][2],data_array[i][3],data_array[i][4],data_array[i][5],data1[i]])
data_x
#data_x

[[26, 43000, 1400, 5, 1110, 1],
 [66, 39144, 1600, 3, 1050, 1],
 [39, 24444, 1600, 3, 1040, 1],
 [65, 59000, 1600, 5, 1075, 1],
 [79, 74093, 1600, 5, 1075, 1],
 [76, 36537, 1600, 4, 1075, 1],
 [39, 40000, 1600, 3, 1055, 1],
 [80, 194765, 2000, 3, 1120, 1],
 [44, 59000, 1600, 5, 1110, 1],
 [77, 93000, 1600, 5, 1075, 1],
 [35, 41000, 1600, 5, 1075, 1],
 [72, 88500, 1600, 5, 1075, 1],
 [47, 45850, 1400, 5, 1060, 1],
 [73, 176177, 1600, 5, 1075, 1],
 [9, 1, 1400, 4, 1065, 1],
 [74, 68285, 1600, 3, 1050, 1],
 [40, 16325, 1600, 5, 1080, 1],
 [29, 9750, 1400, 3, 1100, 1],
 [19, 19200, 1400, 3, 1100, 1],
 [69, 42800, 1600, 3, 1050, 1],
 [42, 61300, 1400, 3, 1030, 1],
 [67, 73936, 1300, 5, 1050, 1],
 [49, 31999, 1400, 3, 1030, 1],
 [54, 63123, 1600, 4, 1035, 1],
 [60, 115191, 1600, 4, 1079, 1],
 [68, 67146, 1600, 5, 1075, 1],
 [68, 53000, 1300, 3, 1015, 1],
 [64, 150585, 1600, 3, 1065, 1],
 [61, 73894, 1600, 3, 1065, 1],
 [77, 121545, 1600, 5, 1070, 1],
 [62, 105000, 1300, 5, 1040, 1],
 [33, 55

In [78]:
tr = math.floor(len(data_x)*75/100)
data_x_tr = data_x[0:tr]
data_x_ts = data_x[tr:]
data_y_tr = data_y[0:tr]
data_y_ts = data_y[tr:]
#data_x_tr
data_y_tr = np.array(data_y_tr)
data_y_ts = np.array(data_y_ts)
data_y_tr

array([[15250],
       [ 8250],
       [12950],
       ...,
       [10950],
       [11250],
       [10850]])

In [79]:
data_x_tr_t = []
data_x_tr_t = np.transpose(data_x_tr)
#data_x_tr_t = data_x_tr.T
data_x_tr_t

array([[   26,    66,    39, ...,    49,    54,    43],
       [43000, 39144, 24444, ..., 53116, 66063, 54600],
       [ 1400,  1600,  1600, ...,  1400,  1600,  1600],
       [    5,     3,     3, ...,     3,     5,     4],
       [ 1110,  1050,  1040, ...,  1025,  1090,  1030],
       [    1,     1,     1, ...,     1,     1,     1]])

In [80]:
data_x_tr=np.array(data_x_tr)
data_x_tr_t=np.array(data_x_tr_t)

#data_y_tr=data_y_tr.T
data_y_tr

array([[15250],
       [ 8250],
       [12950],
       ...,
       [10950],
       [11250],
       [10850]])

In [81]:
#w1 = np.dot(data_x_tr_t, data_x_tr)
w1 = data_x_tr_t @ data_x_tr
w1 = np.linalg.inv(w1)# @ data_x_tr_t @ data_y_tr
print(w1)
#w = np.dot(w1, data_x_tr_t)
#w = np.dot(w, data_y_tr)
w = w1 @ data_x_tr_t @ data_y_tr

[[ 4.77782262e-06 -1.15393221e-09 -7.02069985e-09 -1.35156089e-06
   7.50417254e-07 -9.77510072e-04]
 [-1.15393221e-09  1.05947470e-12 -8.24909209e-11  1.59722180e-10
   1.55942661e-11  1.04306981e-07]
 [-7.02069985e-09 -8.24909209e-11  5.39335992e-08  6.25127575e-07
  -1.25851137e-07  5.40100774e-05]
 [-1.35156089e-06  1.59722180e-10  6.25127575e-07  1.13246726e-03
  -7.64669266e-06  2.70304615e-03]
 [ 7.50417254e-07  1.55942661e-11 -1.25851137e-07 -7.64669266e-06
   7.60294895e-07 -6.30717408e-04]
 [-9.77510072e-04  1.04306981e-07  5.40100774e-05  2.70304615e-03
  -6.30717408e-04  6.29743445e-01]]


In [82]:
y_A = np.dot( data_x_ts, w)
y_A

array([[ 9231.1410948 ],
       [ 9168.77117635],
       [ 8235.72803704],
       [14552.44204712],
       [ 8196.86888495],
       [12550.0623186 ],
       [10375.92261716],
       [12798.39800811],
       [16748.78077285],
       [ 9769.14857114],
       [11431.54995775],
       [11226.4899584 ],
       [ 7278.44761748],
       [ 6252.27456011],
       [ 9078.70110251],
       [11562.89727439],
       [15433.39871588],
       [10651.23075097],
       [12299.78979543],
       [ 7633.03658429],
       [ 8504.99411484],
       [13697.00481904],
       [ 8992.46211053],
       [ 9566.51048507],
       [15912.68051883],
       [ 9258.64776188],
       [ 6966.82313016],
       [14136.83833395],
       [ 7417.91783049],
       [ 8096.55937788],
       [ 9039.88753576],
       [ 9641.53809719],
       [16078.90335037],
       [ 7783.9166234 ],
       [ 7429.77067461],
       [ 9880.11491241],
       [11943.12576452],
       [ 6677.02920606],
       [ 9048.93138248],
       [15695.39617452],
